.\" Manpage for xz-prog
.\" Contact d.wrickey@gmail.com to correct errors or typos
.TH XZ-PROG 1 "14 December 2025" "1.0" "User Commands"
.SH NAME
xv-prog \- Compress a file/directory and visualize its progress
.SH SYNOPSIS
.B xz-prog
\fI\-h\fR
.br
.B xz-prog
[\fIoptions\fR]
\fItarget\fR
.SH DESCRIPTION
.B xz-prog
is a utilty for compressing files and/or folders using XZ compression
.SH OPTIONS
.SH EXAMPLES
.SH "SEE ALSO"
.SH BUGS
.SH AUTHOR
.SH COPYRIGHT

