name: Check Source Branch
on:
  pull_request:
    branches:
      - main

jobs:
  check_source:
    runs-on: ubuntu-latest
    steps:
      - name: "Verify release->main"
        if: github.base_ref == 'main' && github.head_ref != 'release'
        run: |
          echo "Error: Pull requests to 'main' must come from 'release'
          exit 1
      - name: "Verify working->release"
        if: github.base_ref == 'release' && github.head_ref != 'working'
        run: |
          echo "Error: Pull requests to 'release' must come from 'working'
          exit 1
