name: Quality Control
on:
  pull_request:
    branches:
      - working

jobs:
  beautify-and-shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Run shellcheck
        uses: azohra/shell-linter@latest
        with:
          severity: error
      - name: Run beautysh
        uses: illvart/beautysh-action@latest
        with:
          args: '#.sh --indent-size 4'
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '[auto] ci: apply shellcheck and beautysh changes'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
